# mkdocs.yml
site_name : FactSage Compound Databases - format and parsing
site_url: https://evnekdev.github.io/factsage-compound-docs/

markdown_extensions:
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css
  
theme:
  name: material
  
nav:
  - Overview : index.md
  - FactSage Compound Module : compound-module.md
  - Viewing Binary files : binary-viewing.md
  - Kaitai layout of Compound Databases : kaitai.md
  - Compound Database block types : block-types.md
  - Comparing databases (Excel + Python) : database-compare.md
    
  
  