# mkdocs.yml
site_name : FactSage Compound Databases - format and parsing
site_url: https://evnekdev.github.io/factsage-compound-docs/


extra_css:
  - stylesheets/extra.css
  
theme:
  name: material
  
nav:
  - Home :
    - Overview : index.md
    - Theoretical basis: theory.md
  
  
  